### ISSUE TITLE
Error to build app to iPhone 5 iOS 10.3.1

### ISSUE THREAD

**Issue by augustocadini** [kodlian/AlamofireXMLRPC#27]
I need a app to iPhone 5, but when I build the code many errors occurrs. In the Readme informs that works in iOS > 9, I'm using iOS 10.3.1 on iPhone.

The erros are like:

`Module 'AlamofireXMLRPC' has no member named 'request'`

I can use this framework on iPhone 5C?
